---
name: Rust

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:  # Label used to access the service container
        image: postgres
        env:
          POSTGRES_PASSWORD: pgpasswd
          POSTGRES_USER: pguser
          POSTGRES_DB: pgdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: DATABASE_URL=postgresql://pguser:pgpasswd@localhost:5432/pgdb cargo test --verbose

  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macos-26-intel
            target: x86_64-apple-darwin

          - os-name: aarch64-apple-darwin
            runs-on: macos-26
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts and release
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: csv-pg-injector
          target: ${{ matrix.platform.target }}
